manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: golioth
      url-base: https://github.com/golioth
    - name: eclipse-zenoh
      url-base: https://github.com/eclipse-zenoh

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: main
      import:
        # By using name-allowlist we can clone only the modules that are
        # strictly needed by the application.
        name-allowlist:
          - cmsis
          - hal_espressif
          - mbedtls
          - mcuboot

    - name: golioth
      repo-path: golioth-firmware-sdk
      remote: golioth
      path: modules/lib/golioth-firmware-sdk
      revision: main
      submodules: true

    - name: zenoh
      repo-path: zenoh-pico
      remote: eclipse-zenoh
      revision: main
      path: modules/lib/zenoh